export interface Imovel {
  id: string,
  tipoMoradiaEspecifico: string,
  cep: string,
  rua: string,
  numero: number,
  bairro: string,
  complemento?: string,
  preco: number,
  imagens?: string[],
  oculto: boolean,
  descricao?: string,
  tipoVaga: string,
  tipoMoradia: string,
  caracteristicas: string[],
  moveisDisponiveis: string[],
  num_banheiro: number,
  num_salaEstar: number,
  num_cozinha: number,
  num_pessoasCasa: number,
  num_pessoasQuarto: number,
  num_garagem: number,
  num_varanda: number,
  num_areaServico: number,
  num_salaJantar: number,
  num_quartos: number,
  proprietario: string,
}